# Generated by Django 5.1.4 on 2025-01-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
    ]
