# Generated by Django 5.1.4 on 2025-01-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_todo_created_at_remove_todo_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Álbum', 'verbose_name_plural': 'Álbuns'},
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='core.user'),
        ),
    ]
